package magnolia.examples

object GenEq50 {
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]

  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]

  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]

  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]

  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]
  Eq.gen[adt.Alphabet]

}
