package magnolia.examples

object GenGadt {
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]

  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]

  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]

  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]

  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]

  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]

  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]

  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]

  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]

  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
  Eq.gen[adt.GTree[String]]
}
