package magnolia.examples

object GenObj {
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]

  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]

  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]

  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]

  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]

  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]

  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]

  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]

  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]

  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]
  Show.gen[adt.Jan.type]

}
