package magnolia.examples

object GenSmall {
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]

  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]

  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]

  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]

  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]

  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]

  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]

  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]

  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]

  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
  Show.gen[adt.Letter]
}
