package magnolia.examples

object GenShow {
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]

  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]

  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]

  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]

  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
  Show.gen[adt.Alphabet]
}
