package magnolia.examples

object GenShowTree {
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]

  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]

  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]

  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]

  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
  Show.gen[adt.Tree]
}
