package magnolia1.tests

sealed trait HugeEnum
object HugeEnum {
  case object Case1 extends HugeEnum
  case object Case2 extends HugeEnum
  case object Case3 extends HugeEnum
  case object Case4 extends HugeEnum
  case object Case5 extends HugeEnum
  case object Case6 extends HugeEnum
  case object Case7 extends HugeEnum
  case object Case8 extends HugeEnum
  case object Case9 extends HugeEnum
  case object Case10 extends HugeEnum
  case object Case11 extends HugeEnum
  case object Case12 extends HugeEnum
  case object Case13 extends HugeEnum
  case object Case14 extends HugeEnum
  case object Case15 extends HugeEnum
  case object Case16 extends HugeEnum
  case object Case17 extends HugeEnum
  case object Case18 extends HugeEnum
  case object Case19 extends HugeEnum
  case object Case20 extends HugeEnum
  case object Case21 extends HugeEnum
  case object Case22 extends HugeEnum
  case object Case23 extends HugeEnum
  case object Case24 extends HugeEnum
  case object Case25 extends HugeEnum
  case object Case26 extends HugeEnum
  case object Case27 extends HugeEnum
  case object Case28 extends HugeEnum
  case object Case29 extends HugeEnum
  case object Case30 extends HugeEnum
  case object Case31 extends HugeEnum
  case object Case32 extends HugeEnum
  case object Case33 extends HugeEnum
  case object Case34 extends HugeEnum
  case object Case35 extends HugeEnum
  case object Case36 extends HugeEnum
  case object Case37 extends HugeEnum
  case object Case38 extends HugeEnum
  case object Case39 extends HugeEnum
  case object Case40 extends HugeEnum
  case object Case41 extends HugeEnum
  case object Case42 extends HugeEnum
  case object Case43 extends HugeEnum
  case object Case44 extends HugeEnum
  case object Case45 extends HugeEnum
  case object Case46 extends HugeEnum
  case object Case47 extends HugeEnum
  case object Case48 extends HugeEnum
  case object Case49 extends HugeEnum
  case object Case50 extends HugeEnum
  case object Case51 extends HugeEnum
  case object Case52 extends HugeEnum
  case object Case53 extends HugeEnum
  case object Case54 extends HugeEnum
  case object Case55 extends HugeEnum
  case object Case56 extends HugeEnum
  case object Case57 extends HugeEnum
  case object Case58 extends HugeEnum
  case object Case59 extends HugeEnum
  case object Case60 extends HugeEnum
  case object Case61 extends HugeEnum
  case object Case62 extends HugeEnum
  case object Case63 extends HugeEnum
  case object Case64 extends HugeEnum
  case object Case65 extends HugeEnum
  case object Case66 extends HugeEnum
  case object Case67 extends HugeEnum
  case object Case68 extends HugeEnum
  case object Case69 extends HugeEnum
  case object Case70 extends HugeEnum
  case object Case71 extends HugeEnum
  case object Case72 extends HugeEnum
  case object Case73 extends HugeEnum
  case object Case74 extends HugeEnum
  case object Case75 extends HugeEnum
  case object Case76 extends HugeEnum
  case object Case77 extends HugeEnum
  case object Case78 extends HugeEnum
  case object Case79 extends HugeEnum
  case object Case80 extends HugeEnum
  case object Case81 extends HugeEnum
  case object Case82 extends HugeEnum
  case object Case83 extends HugeEnum
  case object Case84 extends HugeEnum
  case object Case85 extends HugeEnum
  case object Case86 extends HugeEnum
  case object Case87 extends HugeEnum
  case object Case88 extends HugeEnum
  case object Case89 extends HugeEnum
  case object Case90 extends HugeEnum
  case object Case91 extends HugeEnum
  case object Case92 extends HugeEnum
  case object Case93 extends HugeEnum
  case object Case94 extends HugeEnum
  case object Case95 extends HugeEnum
  case object Case96 extends HugeEnum
  case object Case97 extends HugeEnum
  case object Case98 extends HugeEnum
  case object Case99 extends HugeEnum
  case object Case100 extends HugeEnum
  case object Case101 extends HugeEnum
  case object Case102 extends HugeEnum
  case object Case103 extends HugeEnum
  case object Case104 extends HugeEnum
  case object Case105 extends HugeEnum
  case object Case106 extends HugeEnum
  case object Case107 extends HugeEnum
  case object Case108 extends HugeEnum
  case object Case109 extends HugeEnum
  case object Case110 extends HugeEnum
  case object Case111 extends HugeEnum
  case object Case112 extends HugeEnum
  case object Case113 extends HugeEnum
  case object Case114 extends HugeEnum
  case object Case115 extends HugeEnum
  case object Case116 extends HugeEnum
  case object Case117 extends HugeEnum
  case object Case118 extends HugeEnum
  case object Case119 extends HugeEnum
  case object Case120 extends HugeEnum
  case object Case121 extends HugeEnum
  case object Case122 extends HugeEnum
  case object Case123 extends HugeEnum
  case object Case124 extends HugeEnum
  case object Case125 extends HugeEnum
  case object Case126 extends HugeEnum
  case object Case127 extends HugeEnum
  case object Case128 extends HugeEnum
  case object Case129 extends HugeEnum
  case object Case130 extends HugeEnum
  case object Case131 extends HugeEnum
  case object Case132 extends HugeEnum
  case object Case133 extends HugeEnum
  case object Case134 extends HugeEnum
  case object Case135 extends HugeEnum
  case object Case136 extends HugeEnum
  case object Case137 extends HugeEnum
  case object Case138 extends HugeEnum
  case object Case139 extends HugeEnum
  case object Case140 extends HugeEnum
  case object Case141 extends HugeEnum
  case object Case142 extends HugeEnum
  case object Case143 extends HugeEnum
  case object Case144 extends HugeEnum
  case object Case145 extends HugeEnum
  case object Case146 extends HugeEnum
  case object Case147 extends HugeEnum
  case object Case148 extends HugeEnum
  case object Case149 extends HugeEnum
  case object Case150 extends HugeEnum
  case object Case151 extends HugeEnum
  case object Case152 extends HugeEnum
  case object Case153 extends HugeEnum
  case object Case154 extends HugeEnum
  case object Case155 extends HugeEnum
  case object Case156 extends HugeEnum
  case object Case157 extends HugeEnum
  case object Case158 extends HugeEnum
  case object Case159 extends HugeEnum
  case object Case160 extends HugeEnum
  case object Case161 extends HugeEnum
  case object Case162 extends HugeEnum
  case object Case163 extends HugeEnum
  case object Case164 extends HugeEnum
  case object Case165 extends HugeEnum
  case object Case166 extends HugeEnum
  case object Case167 extends HugeEnum
  case object Case168 extends HugeEnum
  case object Case169 extends HugeEnum
  case object Case170 extends HugeEnum
  case object Case171 extends HugeEnum
  case object Case172 extends HugeEnum
  case object Case173 extends HugeEnum
  case object Case174 extends HugeEnum
  case object Case175 extends HugeEnum
  case object Case176 extends HugeEnum
  case object Case177 extends HugeEnum
  case object Case178 extends HugeEnum
  case object Case179 extends HugeEnum
  case object Case180 extends HugeEnum
  case object Case181 extends HugeEnum
  case object Case182 extends HugeEnum
  case object Case183 extends HugeEnum
  case object Case184 extends HugeEnum
  case object Case185 extends HugeEnum
  case object Case186 extends HugeEnum
  case object Case187 extends HugeEnum
  case object Case188 extends HugeEnum
  case object Case189 extends HugeEnum
  case object Case190 extends HugeEnum
  case object Case191 extends HugeEnum
  case object Case192 extends HugeEnum
  case object Case193 extends HugeEnum
  case object Case194 extends HugeEnum
  case object Case195 extends HugeEnum
  case object Case196 extends HugeEnum
  case object Case197 extends HugeEnum
  case object Case198 extends HugeEnum
  case object Case199 extends HugeEnum
  case object Case200 extends HugeEnum
  case object Case201 extends HugeEnum
  case object Case202 extends HugeEnum
  case object Case203 extends HugeEnum
  case object Case204 extends HugeEnum
  case object Case205 extends HugeEnum
  case object Case206 extends HugeEnum
  case object Case207 extends HugeEnum
  case object Case208 extends HugeEnum
  case object Case209 extends HugeEnum
  case object Case210 extends HugeEnum
  case object Case211 extends HugeEnum
  case object Case212 extends HugeEnum
  case object Case213 extends HugeEnum
  case object Case214 extends HugeEnum
  case object Case215 extends HugeEnum
  case object Case216 extends HugeEnum
  case object Case217 extends HugeEnum
  case object Case218 extends HugeEnum
  case object Case219 extends HugeEnum
  case object Case220 extends HugeEnum
  case object Case221 extends HugeEnum
  case object Case222 extends HugeEnum
  case object Case223 extends HugeEnum
  case object Case224 extends HugeEnum
  case object Case225 extends HugeEnum
  case object Case226 extends HugeEnum
  case object Case227 extends HugeEnum
  case object Case228 extends HugeEnum
  case object Case229 extends HugeEnum
  case object Case230 extends HugeEnum
  case object Case231 extends HugeEnum
  case object Case232 extends HugeEnum
  case object Case233 extends HugeEnum
  case object Case234 extends HugeEnum
  case object Case235 extends HugeEnum
  case object Case236 extends HugeEnum
  case object Case237 extends HugeEnum
  case object Case238 extends HugeEnum
  case object Case239 extends HugeEnum
  case object Case240 extends HugeEnum
  case object Case241 extends HugeEnum
  case object Case242 extends HugeEnum
  case object Case243 extends HugeEnum
  case object Case244 extends HugeEnum
  case object Case245 extends HugeEnum
  case object Case246 extends HugeEnum
  case object Case247 extends HugeEnum
  case object Case248 extends HugeEnum
  case object Case249 extends HugeEnum
  case object Case250 extends HugeEnum
  case object Case251 extends HugeEnum
  case object Case252 extends HugeEnum
  case object Case253 extends HugeEnum
  case object Case254 extends HugeEnum
  case object Case255 extends HugeEnum
  case object Case256 extends HugeEnum
  case object Case257 extends HugeEnum
  case object Case258 extends HugeEnum
  case object Case259 extends HugeEnum
  case object Case260 extends HugeEnum
  case object Case261 extends HugeEnum
  case object Case262 extends HugeEnum
  case object Case263 extends HugeEnum
  case object Case264 extends HugeEnum
  case object Case265 extends HugeEnum
  case object Case266 extends HugeEnum
  case object Case267 extends HugeEnum
  case object Case268 extends HugeEnum
  case object Case269 extends HugeEnum
  case object Case270 extends HugeEnum
  case object Case271 extends HugeEnum
  case object Case272 extends HugeEnum
  case object Case273 extends HugeEnum
  case object Case274 extends HugeEnum
  case object Case275 extends HugeEnum
  case object Case276 extends HugeEnum
  case object Case277 extends HugeEnum
  case object Case278 extends HugeEnum
  case object Case279 extends HugeEnum
  case object Case280 extends HugeEnum
  case object Case281 extends HugeEnum
  case object Case282 extends HugeEnum
  case object Case283 extends HugeEnum
  case object Case284 extends HugeEnum
  case object Case285 extends HugeEnum
  case object Case286 extends HugeEnum
  case object Case287 extends HugeEnum
  case object Case288 extends HugeEnum
  case object Case289 extends HugeEnum
  case object Case290 extends HugeEnum
  case object Case291 extends HugeEnum
  case object Case292 extends HugeEnum
  case object Case293 extends HugeEnum
  case object Case294 extends HugeEnum
  case object Case295 extends HugeEnum
  case object Case296 extends HugeEnum
  case object Case297 extends HugeEnum
  case object Case298 extends HugeEnum
  case object Case299 extends HugeEnum
  case object Case300 extends HugeEnum
  case object Case301 extends HugeEnum
  case object Case302 extends HugeEnum
  case object Case303 extends HugeEnum
  case object Case304 extends HugeEnum
  case object Case305 extends HugeEnum
  case object Case306 extends HugeEnum
  case object Case307 extends HugeEnum
  case object Case308 extends HugeEnum
  case object Case309 extends HugeEnum
  case object Case310 extends HugeEnum
  case object Case311 extends HugeEnum
  case object Case312 extends HugeEnum
  case object Case313 extends HugeEnum
  case object Case314 extends HugeEnum
  case object Case315 extends HugeEnum
  case object Case316 extends HugeEnum
  case object Case317 extends HugeEnum
  case object Case318 extends HugeEnum
  case object Case319 extends HugeEnum
  case object Case320 extends HugeEnum
  case object Case321 extends HugeEnum
  case object Case322 extends HugeEnum
  case object Case323 extends HugeEnum
  case object Case324 extends HugeEnum
  case object Case325 extends HugeEnum
  case object Case326 extends HugeEnum
  case object Case327 extends HugeEnum
  case object Case328 extends HugeEnum
  case object Case329 extends HugeEnum
  case object Case330 extends HugeEnum
  case object Case331 extends HugeEnum
  case object Case332 extends HugeEnum
  case object Case333 extends HugeEnum
  case object Case334 extends HugeEnum
  case object Case335 extends HugeEnum
  case object Case336 extends HugeEnum
  case object Case337 extends HugeEnum
  case object Case338 extends HugeEnum
  case object Case339 extends HugeEnum
  case object Case340 extends HugeEnum
  case object Case341 extends HugeEnum
  case object Case342 extends HugeEnum
  case object Case343 extends HugeEnum
  case object Case344 extends HugeEnum
  case object Case345 extends HugeEnum
  case object Case346 extends HugeEnum
  case object Case347 extends HugeEnum
  case object Case348 extends HugeEnum
  case object Case349 extends HugeEnum
  case object Case350 extends HugeEnum
  case object Case351 extends HugeEnum
  case object Case352 extends HugeEnum
  case object Case353 extends HugeEnum
  case object Case354 extends HugeEnum
  case object Case355 extends HugeEnum
  case object Case356 extends HugeEnum
  case object Case357 extends HugeEnum
  case object Case358 extends HugeEnum
  case object Case359 extends HugeEnum
  case object Case360 extends HugeEnum
  case object Case361 extends HugeEnum
  case object Case362 extends HugeEnum
  case object Case363 extends HugeEnum
  case object Case364 extends HugeEnum
  case object Case365 extends HugeEnum
  case object Case366 extends HugeEnum
  case object Case367 extends HugeEnum
  case object Case368 extends HugeEnum
  case object Case369 extends HugeEnum
  case object Case370 extends HugeEnum
  case object Case371 extends HugeEnum
  case object Case372 extends HugeEnum
  case object Case373 extends HugeEnum
  case object Case374 extends HugeEnum
  case object Case375 extends HugeEnum
  case object Case376 extends HugeEnum
  case object Case377 extends HugeEnum
  case object Case378 extends HugeEnum
  case object Case379 extends HugeEnum
  case object Case380 extends HugeEnum
  case object Case381 extends HugeEnum
  case object Case382 extends HugeEnum
  case object Case383 extends HugeEnum
  case object Case384 extends HugeEnum
  case object Case385 extends HugeEnum
  case object Case386 extends HugeEnum
  case object Case387 extends HugeEnum
  case object Case388 extends HugeEnum
  case object Case389 extends HugeEnum
  case object Case390 extends HugeEnum
  case object Case391 extends HugeEnum
  case object Case392 extends HugeEnum
  case object Case393 extends HugeEnum
  case object Case394 extends HugeEnum
  case object Case395 extends HugeEnum
  case object Case396 extends HugeEnum
  case object Case397 extends HugeEnum
  case object Case398 extends HugeEnum
  case object Case399 extends HugeEnum
  case object Case400 extends HugeEnum
  case object Case401 extends HugeEnum
  case object Case402 extends HugeEnum
  case object Case403 extends HugeEnum
  case object Case404 extends HugeEnum
  case object Case405 extends HugeEnum
  case object Case406 extends HugeEnum
  case object Case407 extends HugeEnum
  case object Case408 extends HugeEnum
  case object Case409 extends HugeEnum
  case object Case410 extends HugeEnum
  case object Case411 extends HugeEnum
  case object Case412 extends HugeEnum
  case object Case413 extends HugeEnum
  case object Case414 extends HugeEnum
  case object Case415 extends HugeEnum
  case object Case416 extends HugeEnum
  case object Case417 extends HugeEnum
  case object Case418 extends HugeEnum
  case object Case419 extends HugeEnum
  case object Case420 extends HugeEnum
  case object Case421 extends HugeEnum
  case object Case422 extends HugeEnum
  case object Case423 extends HugeEnum
  case object Case424 extends HugeEnum
  case object Case425 extends HugeEnum
  case object Case426 extends HugeEnum
  case object Case427 extends HugeEnum
  case object Case428 extends HugeEnum
  case object Case429 extends HugeEnum
  case object Case430 extends HugeEnum
  case object Case431 extends HugeEnum
  case object Case432 extends HugeEnum
  case object Case433 extends HugeEnum
  case object Case434 extends HugeEnum
  case object Case435 extends HugeEnum
  case object Case436 extends HugeEnum
  case object Case437 extends HugeEnum
  case object Case438 extends HugeEnum
  case object Case439 extends HugeEnum
  case object Case440 extends HugeEnum
  case object Case441 extends HugeEnum
  case object Case442 extends HugeEnum
  case object Case443 extends HugeEnum
  case object Case444 extends HugeEnum
  case object Case445 extends HugeEnum
  case object Case446 extends HugeEnum
  case object Case447 extends HugeEnum
  case object Case448 extends HugeEnum
  case object Case449 extends HugeEnum
  case object Case450 extends HugeEnum
  case object Case451 extends HugeEnum
  case object Case452 extends HugeEnum
  case object Case453 extends HugeEnum
  case object Case454 extends HugeEnum
  case object Case455 extends HugeEnum
  case object Case456 extends HugeEnum
  case object Case457 extends HugeEnum
  case object Case458 extends HugeEnum
  case object Case459 extends HugeEnum
  case object Case460 extends HugeEnum
  case object Case461 extends HugeEnum
  case object Case462 extends HugeEnum
  case object Case463 extends HugeEnum
  case object Case464 extends HugeEnum
  case object Case465 extends HugeEnum
  case object Case466 extends HugeEnum
  case object Case467 extends HugeEnum
  case object Case468 extends HugeEnum
  case object Case469 extends HugeEnum
  case object Case470 extends HugeEnum
  case object Case471 extends HugeEnum
  case object Case472 extends HugeEnum
  case object Case473 extends HugeEnum
  case object Case474 extends HugeEnum
  case object Case475 extends HugeEnum
  case object Case476 extends HugeEnum
  case object Case477 extends HugeEnum
  case object Case478 extends HugeEnum
  case object Case479 extends HugeEnum
  case object Case480 extends HugeEnum
  case object Case481 extends HugeEnum
  case object Case482 extends HugeEnum
  case object Case483 extends HugeEnum
  case object Case484 extends HugeEnum
  case object Case485 extends HugeEnum
  case object Case486 extends HugeEnum
  case object Case487 extends HugeEnum
  case object Case488 extends HugeEnum
  case object Case489 extends HugeEnum
  case object Case490 extends HugeEnum
  case object Case491 extends HugeEnum
  case object Case492 extends HugeEnum
  case object Case493 extends HugeEnum
  case object Case494 extends HugeEnum
  case object Case495 extends HugeEnum
  case object Case496 extends HugeEnum
  case object Case497 extends HugeEnum
  case object Case498 extends HugeEnum
  case object Case499 extends HugeEnum
  case object Case500 extends HugeEnum
  case object Case501 extends HugeEnum
  case object Case502 extends HugeEnum
  case object Case503 extends HugeEnum
  case object Case504 extends HugeEnum
  case object Case505 extends HugeEnum
  case object Case506 extends HugeEnum
  case object Case507 extends HugeEnum
  case object Case508 extends HugeEnum
  case object Case509 extends HugeEnum
  case object Case510 extends HugeEnum
  case object Case511 extends HugeEnum
  case object Case512 extends HugeEnum
  case object Case513 extends HugeEnum
  case object Case514 extends HugeEnum
  case object Case515 extends HugeEnum
  case object Case516 extends HugeEnum
  case object Case517 extends HugeEnum
  case object Case518 extends HugeEnum
  case object Case519 extends HugeEnum
  case object Case520 extends HugeEnum
  case object Case521 extends HugeEnum
  case object Case522 extends HugeEnum
  case object Case523 extends HugeEnum
  case object Case524 extends HugeEnum
  case object Case525 extends HugeEnum
  case object Case526 extends HugeEnum
  case object Case527 extends HugeEnum
  case object Case528 extends HugeEnum
  case object Case529 extends HugeEnum
  case object Case530 extends HugeEnum
  case object Case531 extends HugeEnum
  case object Case532 extends HugeEnum
  case object Case533 extends HugeEnum
  case object Case534 extends HugeEnum
  case object Case535 extends HugeEnum
  case object Case536 extends HugeEnum
  case object Case537 extends HugeEnum
  case object Case538 extends HugeEnum
  case object Case539 extends HugeEnum
  case object Case540 extends HugeEnum
  case object Case541 extends HugeEnum
  case object Case542 extends HugeEnum
  case object Case543 extends HugeEnum
  case object Case544 extends HugeEnum
  case object Case545 extends HugeEnum
  case object Case546 extends HugeEnum
  case object Case547 extends HugeEnum
  case object Case548 extends HugeEnum
  case object Case549 extends HugeEnum
  case object Case550 extends HugeEnum
  case object Case551 extends HugeEnum
  case object Case552 extends HugeEnum
  case object Case553 extends HugeEnum
  case object Case554 extends HugeEnum
  case object Case555 extends HugeEnum
  case object Case556 extends HugeEnum
  case object Case557 extends HugeEnum
  case object Case558 extends HugeEnum
  case object Case559 extends HugeEnum
  case object Case560 extends HugeEnum
  case object Case561 extends HugeEnum
  case object Case562 extends HugeEnum
  case object Case563 extends HugeEnum
  case object Case564 extends HugeEnum
  case object Case565 extends HugeEnum
  case object Case566 extends HugeEnum
  case object Case567 extends HugeEnum
  case object Case568 extends HugeEnum
  case object Case569 extends HugeEnum
  case object Case570 extends HugeEnum
  case object Case571 extends HugeEnum
  case object Case572 extends HugeEnum
  case object Case573 extends HugeEnum
  case object Case574 extends HugeEnum
  case object Case575 extends HugeEnum
  case object Case576 extends HugeEnum
  case object Case577 extends HugeEnum
  case object Case578 extends HugeEnum
  case object Case579 extends HugeEnum
  case object Case580 extends HugeEnum
  case object Case581 extends HugeEnum
  case object Case582 extends HugeEnum
  case object Case583 extends HugeEnum
  case object Case584 extends HugeEnum
  case object Case585 extends HugeEnum
  case object Case586 extends HugeEnum
  case object Case587 extends HugeEnum
  case object Case588 extends HugeEnum
  case object Case589 extends HugeEnum
  case object Case590 extends HugeEnum
  case object Case591 extends HugeEnum
  case object Case592 extends HugeEnum
  case object Case593 extends HugeEnum
  case object Case594 extends HugeEnum
  case object Case595 extends HugeEnum
  case object Case596 extends HugeEnum
  case object Case597 extends HugeEnum
  case object Case598 extends HugeEnum
  case object Case599 extends HugeEnum
  case object Case600 extends HugeEnum
  case object Case601 extends HugeEnum
  case object Case602 extends HugeEnum
  case object Case603 extends HugeEnum
  case object Case604 extends HugeEnum
  case object Case605 extends HugeEnum
  case object Case606 extends HugeEnum
  case object Case607 extends HugeEnum
  case object Case608 extends HugeEnum
  case object Case609 extends HugeEnum
  case object Case610 extends HugeEnum
  case object Case611 extends HugeEnum
  case object Case612 extends HugeEnum
  case object Case613 extends HugeEnum
  case object Case614 extends HugeEnum
  case object Case615 extends HugeEnum
  case object Case616 extends HugeEnum
  case object Case617 extends HugeEnum
  case object Case618 extends HugeEnum
  case object Case619 extends HugeEnum
  case object Case620 extends HugeEnum
  case object Case621 extends HugeEnum
  case object Case622 extends HugeEnum
  case object Case623 extends HugeEnum
  case object Case624 extends HugeEnum
  case object Case625 extends HugeEnum
  case object Case626 extends HugeEnum
  case object Case627 extends HugeEnum
  case object Case628 extends HugeEnum
  case object Case629 extends HugeEnum
  case object Case630 extends HugeEnum
  case object Case631 extends HugeEnum
  case object Case632 extends HugeEnum
  case object Case633 extends HugeEnum
  case object Case634 extends HugeEnum
  case object Case635 extends HugeEnum
  case object Case636 extends HugeEnum
  case object Case637 extends HugeEnum
  case object Case638 extends HugeEnum
  case object Case639 extends HugeEnum
  case object Case640 extends HugeEnum
  case object Case641 extends HugeEnum
  case object Case642 extends HugeEnum
  case object Case643 extends HugeEnum
  case object Case644 extends HugeEnum
  case object Case645 extends HugeEnum
  case object Case646 extends HugeEnum
  case object Case647 extends HugeEnum
  case object Case648 extends HugeEnum
  case object Case649 extends HugeEnum
  case object Case650 extends HugeEnum
  case object Case651 extends HugeEnum
  case object Case652 extends HugeEnum
  case object Case653 extends HugeEnum
  case object Case654 extends HugeEnum
  case object Case655 extends HugeEnum
  case object Case656 extends HugeEnum
  case object Case657 extends HugeEnum
  case object Case658 extends HugeEnum
  case object Case659 extends HugeEnum
  case object Case660 extends HugeEnum
  case object Case661 extends HugeEnum
  case object Case662 extends HugeEnum
  case object Case663 extends HugeEnum
  case object Case664 extends HugeEnum
  case object Case665 extends HugeEnum
  case object Case666 extends HugeEnum
  case object Case667 extends HugeEnum
  case object Case668 extends HugeEnum
  case object Case669 extends HugeEnum
  case object Case670 extends HugeEnum
  case object Case671 extends HugeEnum
  case object Case672 extends HugeEnum
  case object Case673 extends HugeEnum
  case object Case674 extends HugeEnum
  case object Case675 extends HugeEnum
  case object Case676 extends HugeEnum
  case object Case677 extends HugeEnum
  case object Case678 extends HugeEnum
  case object Case679 extends HugeEnum
  case object Case680 extends HugeEnum
  case object Case681 extends HugeEnum
  case object Case682 extends HugeEnum
  case object Case683 extends HugeEnum
  case object Case684 extends HugeEnum
  case object Case685 extends HugeEnum
  case object Case686 extends HugeEnum
  case object Case687 extends HugeEnum
  case object Case688 extends HugeEnum
  case object Case689 extends HugeEnum
  case object Case690 extends HugeEnum
  case object Case691 extends HugeEnum
  case object Case692 extends HugeEnum
  case object Case693 extends HugeEnum
  case object Case694 extends HugeEnum
  case object Case695 extends HugeEnum
  case object Case696 extends HugeEnum
  case object Case697 extends HugeEnum
  case object Case698 extends HugeEnum
  case object Case699 extends HugeEnum
  case object Case700 extends HugeEnum
  case object Case701 extends HugeEnum
  case object Case702 extends HugeEnum
  case object Case703 extends HugeEnum
  case object Case704 extends HugeEnum
  case object Case705 extends HugeEnum
  case object Case706 extends HugeEnum
  case object Case707 extends HugeEnum
  case object Case708 extends HugeEnum
  case object Case709 extends HugeEnum
  case object Case710 extends HugeEnum
  case object Case711 extends HugeEnum
  case object Case712 extends HugeEnum
  case object Case713 extends HugeEnum
  case object Case714 extends HugeEnum
  case object Case715 extends HugeEnum
  case object Case716 extends HugeEnum
  case object Case717 extends HugeEnum
  case object Case718 extends HugeEnum
  case object Case719 extends HugeEnum
  case object Case720 extends HugeEnum
  case object Case721 extends HugeEnum
  case object Case722 extends HugeEnum
  case object Case723 extends HugeEnum
  case object Case724 extends HugeEnum
  case object Case725 extends HugeEnum
  case object Case726 extends HugeEnum
  case object Case727 extends HugeEnum
  case object Case728 extends HugeEnum
  case object Case729 extends HugeEnum
  case object Case730 extends HugeEnum
  case object Case731 extends HugeEnum
  case object Case732 extends HugeEnum
  case object Case733 extends HugeEnum
  case object Case734 extends HugeEnum
  case object Case735 extends HugeEnum
  case object Case736 extends HugeEnum
  case object Case737 extends HugeEnum
  case object Case738 extends HugeEnum
  case object Case739 extends HugeEnum
  case object Case740 extends HugeEnum
  case object Case741 extends HugeEnum
  case object Case742 extends HugeEnum
  case object Case743 extends HugeEnum
  case object Case744 extends HugeEnum
  case object Case745 extends HugeEnum
  case object Case746 extends HugeEnum
  case object Case747 extends HugeEnum
  case object Case748 extends HugeEnum
  case object Case749 extends HugeEnum
  case object Case750 extends HugeEnum
  case object Case751 extends HugeEnum
  case object Case752 extends HugeEnum
  case object Case753 extends HugeEnum
  case object Case754 extends HugeEnum
  case object Case755 extends HugeEnum
  case object Case756 extends HugeEnum
  case object Case757 extends HugeEnum
  case object Case758 extends HugeEnum
  case object Case759 extends HugeEnum
  case object Case760 extends HugeEnum
  case object Case761 extends HugeEnum
  case object Case762 extends HugeEnum
  case object Case763 extends HugeEnum
  case object Case764 extends HugeEnum
  case object Case765 extends HugeEnum
  case object Case766 extends HugeEnum
  case object Case767 extends HugeEnum
  case object Case768 extends HugeEnum
  case object Case769 extends HugeEnum
  case object Case770 extends HugeEnum
  case object Case771 extends HugeEnum
  case object Case772 extends HugeEnum
  case object Case773 extends HugeEnum
  case object Case774 extends HugeEnum
  case object Case775 extends HugeEnum
  case object Case776 extends HugeEnum
  case object Case777 extends HugeEnum
  case object Case778 extends HugeEnum
  case object Case779 extends HugeEnum
  case object Case780 extends HugeEnum
  case object Case781 extends HugeEnum
  case object Case782 extends HugeEnum
  case object Case783 extends HugeEnum
  case object Case784 extends HugeEnum
  case object Case785 extends HugeEnum
  case object Case786 extends HugeEnum
  case object Case787 extends HugeEnum
  case object Case788 extends HugeEnum
  case object Case789 extends HugeEnum
  case object Case790 extends HugeEnum
  case object Case791 extends HugeEnum
  case object Case792 extends HugeEnum
  case object Case793 extends HugeEnum
  case object Case794 extends HugeEnum
  case object Case795 extends HugeEnum
  case object Case796 extends HugeEnum
  case object Case797 extends HugeEnum
  case object Case798 extends HugeEnum
  case object Case799 extends HugeEnum
  case object Case800 extends HugeEnum
  case object Case801 extends HugeEnum
  case object Case802 extends HugeEnum
  case object Case803 extends HugeEnum
  case object Case804 extends HugeEnum
  case object Case805 extends HugeEnum
  case object Case806 extends HugeEnum
  case object Case807 extends HugeEnum
  case object Case808 extends HugeEnum
  case object Case809 extends HugeEnum
  case object Case810 extends HugeEnum
  case object Case811 extends HugeEnum
  case object Case812 extends HugeEnum
  case object Case813 extends HugeEnum
  case object Case814 extends HugeEnum
  case object Case815 extends HugeEnum
  case object Case816 extends HugeEnum
  case object Case817 extends HugeEnum
  case object Case818 extends HugeEnum
  case object Case819 extends HugeEnum
  case object Case820 extends HugeEnum
  case object Case821 extends HugeEnum
  case object Case822 extends HugeEnum
  case object Case823 extends HugeEnum
  case object Case824 extends HugeEnum
  case object Case825 extends HugeEnum
  case object Case826 extends HugeEnum
  case object Case827 extends HugeEnum
  case object Case828 extends HugeEnum
  case object Case829 extends HugeEnum
  case object Case830 extends HugeEnum
  case object Case831 extends HugeEnum
  case object Case832 extends HugeEnum
  case object Case833 extends HugeEnum
  case object Case834 extends HugeEnum
  case object Case835 extends HugeEnum
  case object Case836 extends HugeEnum
  case object Case837 extends HugeEnum
  case object Case838 extends HugeEnum
  case object Case839 extends HugeEnum
  case object Case840 extends HugeEnum
  case object Case841 extends HugeEnum
  case object Case842 extends HugeEnum
  case object Case843 extends HugeEnum
  case object Case844 extends HugeEnum
  case object Case845 extends HugeEnum
  case object Case846 extends HugeEnum
  case object Case847 extends HugeEnum
  case object Case848 extends HugeEnum
  case object Case849 extends HugeEnum
  case object Case850 extends HugeEnum
  case object Case851 extends HugeEnum
  case object Case852 extends HugeEnum
  case object Case853 extends HugeEnum
  case object Case854 extends HugeEnum
  case object Case855 extends HugeEnum
  case object Case856 extends HugeEnum
  case object Case857 extends HugeEnum
  case object Case858 extends HugeEnum
  case object Case859 extends HugeEnum
  case object Case860 extends HugeEnum
  case object Case861 extends HugeEnum
  case object Case862 extends HugeEnum
  case object Case863 extends HugeEnum
  case object Case864 extends HugeEnum
  case object Case865 extends HugeEnum
  case object Case866 extends HugeEnum
  case object Case867 extends HugeEnum
  case object Case868 extends HugeEnum
  case object Case869 extends HugeEnum
  case object Case870 extends HugeEnum
  case object Case871 extends HugeEnum
  case object Case872 extends HugeEnum
  case object Case873 extends HugeEnum
  case object Case874 extends HugeEnum
  case object Case875 extends HugeEnum
  case object Case876 extends HugeEnum
  case object Case877 extends HugeEnum
  case object Case878 extends HugeEnum
  case object Case879 extends HugeEnum
  case object Case880 extends HugeEnum
  case object Case881 extends HugeEnum
  case object Case882 extends HugeEnum
  case object Case883 extends HugeEnum
  case object Case884 extends HugeEnum
  case object Case885 extends HugeEnum
  case object Case886 extends HugeEnum
  case object Case887 extends HugeEnum
  case object Case888 extends HugeEnum
  case object Case889 extends HugeEnum
  case object Case890 extends HugeEnum
  case object Case891 extends HugeEnum
  case object Case892 extends HugeEnum
  case object Case893 extends HugeEnum
  case object Case894 extends HugeEnum
  case object Case895 extends HugeEnum
  case object Case896 extends HugeEnum
  case object Case897 extends HugeEnum
  case object Case898 extends HugeEnum
  case object Case899 extends HugeEnum
  case object Case900 extends HugeEnum
  case object Case901 extends HugeEnum
  case object Case902 extends HugeEnum
  case object Case903 extends HugeEnum
  case object Case904 extends HugeEnum
  case object Case905 extends HugeEnum
  case object Case906 extends HugeEnum
  case object Case907 extends HugeEnum
  case object Case908 extends HugeEnum
  case object Case909 extends HugeEnum
  case object Case910 extends HugeEnum
  case object Case911 extends HugeEnum
  case object Case912 extends HugeEnum
  case object Case913 extends HugeEnum
  case object Case914 extends HugeEnum
  case object Case915 extends HugeEnum
  case object Case916 extends HugeEnum
  case object Case917 extends HugeEnum
  case object Case918 extends HugeEnum
  case object Case919 extends HugeEnum
  case object Case920 extends HugeEnum
  case object Case921 extends HugeEnum
  case object Case922 extends HugeEnum
  case object Case923 extends HugeEnum
  case object Case924 extends HugeEnum
  case object Case925 extends HugeEnum
  case object Case926 extends HugeEnum
  case object Case927 extends HugeEnum
  case object Case928 extends HugeEnum
  case object Case929 extends HugeEnum
  case object Case930 extends HugeEnum
  case object Case931 extends HugeEnum
  case object Case932 extends HugeEnum
  case object Case933 extends HugeEnum
  case object Case934 extends HugeEnum
  case object Case935 extends HugeEnum
  case object Case936 extends HugeEnum
  case object Case937 extends HugeEnum
  case object Case938 extends HugeEnum
  case object Case939 extends HugeEnum
  case object Case940 extends HugeEnum
  case object Case941 extends HugeEnum
  case object Case942 extends HugeEnum
  case object Case943 extends HugeEnum
  case object Case944 extends HugeEnum
  case object Case945 extends HugeEnum
  case object Case946 extends HugeEnum
  case object Case947 extends HugeEnum
  case object Case948 extends HugeEnum
  case object Case949 extends HugeEnum
  case object Case950 extends HugeEnum
  case object Case951 extends HugeEnum
  case object Case952 extends HugeEnum
  case object Case953 extends HugeEnum
  case object Case954 extends HugeEnum
  case object Case955 extends HugeEnum
  case object Case956 extends HugeEnum
  case object Case957 extends HugeEnum
  case object Case958 extends HugeEnum
  case object Case959 extends HugeEnum
  case object Case960 extends HugeEnum
  case object Case961 extends HugeEnum
  case object Case962 extends HugeEnum
  case object Case963 extends HugeEnum
  case object Case964 extends HugeEnum
  case object Case965 extends HugeEnum
  case object Case966 extends HugeEnum
  case object Case967 extends HugeEnum
  case object Case968 extends HugeEnum
  case object Case969 extends HugeEnum
  case object Case970 extends HugeEnum
  case object Case971 extends HugeEnum
  case object Case972 extends HugeEnum
  case object Case973 extends HugeEnum
  case object Case974 extends HugeEnum
  case object Case975 extends HugeEnum
  case object Case976 extends HugeEnum
  case object Case977 extends HugeEnum
  case object Case978 extends HugeEnum
  case object Case979 extends HugeEnum
  case object Case980 extends HugeEnum
  case object Case981 extends HugeEnum
  case object Case982 extends HugeEnum
  case object Case983 extends HugeEnum
  case object Case984 extends HugeEnum
  case object Case985 extends HugeEnum
  case object Case986 extends HugeEnum
  case object Case987 extends HugeEnum
  case object Case988 extends HugeEnum
  case object Case989 extends HugeEnum
  case object Case990 extends HugeEnum
  case object Case991 extends HugeEnum
  case object Case992 extends HugeEnum
  case object Case993 extends HugeEnum
  case object Case994 extends HugeEnum
  case object Case995 extends HugeEnum
  case object Case996 extends HugeEnum
  case object Case997 extends HugeEnum
  case object Case998 extends HugeEnum
  case object Case999 extends HugeEnum
  case object Case1000 extends HugeEnum
}
